main = "dist/index.js"

compatibility_date = "2024-08-26"
compatibility_flags = [ "nodejs_compat" ]

[env.dev]
vars = { ALLOWED_HOST = "*", ENV = "dev" }
[[env.dev.kv_namespaces]]
binding = "LOCAL_DB"
id = "local-db"

[env.test]
vars = { ALLOWED_HOST = "*", ENV = "test" }
[[env.test.kv_namespaces]]
binding = "TEST_DB"
id = "test-db"

[env.stage]
name = "todo-rename-stage"
workers_dev = true
vars = { ALLOWED_HOST = "todo:rename to stage host", ENV = "stage" }
[[env.stage.kv_namespaces]]
binding = "DB"
id = "todo:stage-db-id"

[env.prod]
name = "todo-rename-prod"
workers_dev = true
vars = { ALLOWED_HOST = "todo:rename to prod host", ENV = "prod" }
[[env.prod.kv_namespaces]]
binding = "DB"
id = "todo:prod-db-id"
